version: '3.8'

services:
  api:
    build: .
    container_name: api_controle_usuario
    ports:
      - "3000:3000"
    depends_on:
      - redis
    volumes:
      - ./:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis:7.2
    container_name: banco_cache_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
