openapi: 3.0.0
info:
  title: Auth API
  version: 1.0.0
  description: API de autenticação com JWT e Redis

servers:
  - url: http://localhost:3000'

paths:
  /auth/register:
    post:
      summary: Registrar novo usuário
      tags: [Authentication]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - email
                - password
              properties:
                name:
                  type: string
                  example: "João Silva"
                email:
                  type: string
                  format: email
                  example: "joao@email.com"
                password:
                  type: string
                  minLength: 6
                  example: "123456"
      responses:
        '201':
          description: Usuário registrado com sucesso
        '400':
          description: Dados inválidos

  /auth/login:
    post:
      summary: Realizar login
      tags: [Authentication]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  example: "joao@email.com"
                password:
                  type: string
                  example: "123456"
      responses:
        '200':
          description: Login realizado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                  user:
                    type: object
        '401':
          description: Credenciais inválidas

  /auth/logout:
    post:
      summary: Realizar logout
      tags: [Authentication]
      security:
        - bearerAuth: []
      description: |
        *Requer header:* Authorization: Bearer <jwt_token>
        
        Adiciona o token à blacklist no Redis com TTL igual ao tempo restante de expiração.
      responses:
        '200':
          description: Logout realizado com sucesso
        '401':
          description: Token inválido, ausente ou revogado

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: "Use: Authorization: Bearer <jwt_token>"